### ISSUE TITLE
pERO CUANTOS ISSUES TIENE ESTE TIO?

### ISSUE THREAD

**Issue by OscarSC** [cristianfernandezcabre/Validacio-Cristian#3]

**Comment by cristianfernandezcabre** [comment]
🤔

**Comment by AreJey** [comment]
pues por lo visto muchos ;/

**Comment by OscarSC** [comment]
unlucky shrug

**Comment by AreJey** [comment]
genji main?

**Comment by OscarSC** [comment]
**REPORTADISIMO**

**Comment by OscarSC** [comment]
[https://vignette3.wikia.nocookie.net/overwatch/images/6/63/Reaper_Spray_-_Shrug.png/revision/latest?cb=20170601222734](url)

**Comment by OscarSC** [comment]
<img src="https://vignette3.wikia.nocookie.net/overwatch/images/6/63/Reaper_Spray_-_Shrug.png/revision/latest?cb=20170601222734">

**Comment by OscarSC** [comment]
cabron abrelo de nuevo
